require(shakespeare)
tp <- Play("tempest")
tp$speeches
last <- tp$speeches$el(640)
ev <- XRPython::RPython()
class(ev$Get(last))
printSpeech(last)
last$findText("free")
last$findText("deliver")
last$findText("prom")
last$findText("prom", tokens = FALSE)
last$findText("promise", ignoreCase = FALSE)
sps <- vector("list", tp$speeches$size())
for(i in seq_along(sps)) sps[[i]] <- tp$speeches$el(i-1)
sizes <- sapply(sps, function(x)x$lines$size())
mx <- which.max(sizes)
printSpeech(sps[[mx]])
sps[[571]]$findText("free", .get=TRUE)
sps[[571]]$findText("that", .get=TRUE)
sp0 <- tp$speeches$el(570)
act5 <- getActs(tp)$el(4)
sp5 <- getSpeeches(act5)
yy = SpeechList(searchSpeeches("free", sp5))
for(i in 0:4) printSpeech(yy$el(i))
hp = Play("hamlet")
hpfree <- speechSearch("nunnery", hp$speeches)
for(i in 0:2) printSpeech(hpfree$el(i))
